### ISSUE TITLE
error closing patch

### ISSUE THREAD

**Issue by joenio** [ircam-ismm/node-libpd#5]
The README.md says to close a patch passing as argument `${patch.$0}-input` like the example below.

```js
const patch = pd.openPatch(patchPathname);
pd.closePatch(`${patch.$0}-input`);
```

But trying this way I was getting some errors, then checking at source-code I have discovered that the `closePatch` function receives as argument the patch object itself, then I changed my code a bit as the example below.

```js
const patch = pd.openPatch(patchPathname);
pd.closePatch(patch);
```

And, in this way I was able to close the patch successfully without any errors.

Is it the right way to close the patch or am I missing something?

BTW, thanks for sharing this amazing piece of work, I really liked the `node-libpd` project.

**Comment by b-ma** [comment]
Hey, yup indeed it looks like a typo in the example, this is fixed now

Thanks!
